version: '2'
services:
  nginx:
    image: nginx
    restart: always
    build:
      context: .
      dockerfile: dockerfileNginx
    links:
      - edge1:edge1
    ports:
      - 2190:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cassandra:
    build:
      dockerfile: dockerCassandra
      context: .
    container_name: cassandra
    restart: on-failure

  eureka:
    build:
      dockerfile: dockerfileEureka
      context: .
    container_name: eureka
    ports:
      - "8080:80"
    privileged: true
    restart: on-failure

  middletier:
    build:
      dockerfile: dockerfileMiddle
      context: .
    links:
      - eureka
      - cassandra
    restart: on-failure

  edge1:
    build:
      context: .
      dockerfile: dockerfileEdge
    links:
      - eureka
      - middletier
    ports:
      - "2190"
    environment:
      - EXCLUDE_PORTS=9092
    restart: on-failure

